// Reads and parses the project's discovery manifest + active tenant context.
// No external YAML dependency — the manifest is machine-generated by
// build_manifest.py with a stable, regular shape, so a small targeted parser
// is sufficient and keeps the extension zero-install.

import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

// Emoji per threat-pulse domain tag (mirrors the repo's Copilot instructions).
export const DOMAIN_ICONS = {
    incidents: "🔴",
    identity: "🔐",
    spn: "🤖",
    endpoint: "🖥️",
    email: "📧",
    admin: "🔑",
    cloud: "☁️",
    exposure: "🛡️",
};

// Skills that have no canned prompt in the manifest but are still worth
// surfacing as launchable cards. Maps skill name -> friendly card metadata.
const UTILITY_SKILL_PROMPTS = {
    "threat-pulse": "Run a Threat Pulse scan across all security domains and give me the prioritized dashboard",
    "kql-query-authoring": "Help me author a KQL query",
    "svg-dashboard": "Generate an SVG dashboard from the latest report",
    "geomap-visualization": "Create a geomap visualization of attack origins",
    "heatmap-visualization": "Create a heatmap visualization of activity patterns",
    "detection-authoring": "Help me create and deploy a custom detection rule",
    "threat-intel-campaign": "Ingest a threat intelligence article and build a hunting campaign",
    "sentinel-ingestion-report": "Run a Sentinel ingestion report — volume, tiers, anomalies, cost",
    "context-memory-review": "Review my tenant-context memory file against the latest scan reports",
};

// Utility skills that shouldn't clutter the launchable grid. They run as part of
// other workflows (e.g. svg-dashboard/geomap/heatmap consume another skill's
// output) or are triggered naturally by chat keywords (kql-query-authoring,
// detection-authoring, threat-intel-campaign, context-memory-review) rather than
// launched cold from a card. Kept in UTILITY_SKILL_PROMPTS so the agent can still
// invoke them, just hidden from the Mission Control grid.
const HIDDEN_SKILLS = new Set([
    "heatmap-visualization",
    "geomap-visualization",
    "svg-dashboard",
    "threat-intel-campaign",
    "kql-query-authoring",
    "detection-authoring",
    "context-memory-review",
]);

// Skills whose {entity} prompt can also run tenant/fleet-wide. When the analyst
// picks "Fleet-wide" on the card, {entity} is replaced with the `phrase` below
// (instead of a single target), so the launched skill sweeps every asset. `label`
// is the short descriptor shown on the card toggle. Keeping this here is the
// single source of truth — the UI reads `fleet` off each skill, and composePrompt
// substitutes the phrase, so the two never drift.
const FLEET_SCOPE = {
    "scope-drift-detection-device": {
        label: "all devices",
        phrase: "the entire device fleet — analyze every device, rank by drift score, and surface the highest-drift outliers",
    },
    "scope-drift-detection-spn": {
        label: "all service principals",
        phrase: "all service principals fleet-wide — rank by drift score and surface the highest-drift outliers",
    },
};

/** Fleet metadata for a skill name, or null when it isn't fleet-capable. */
export function fleetScope(name) {
    return FLEET_SCOPE[name] || null;
}

/**
 * Minimal parser for the slim discovery manifest. Returns { skills, queries }.
 * Each skill: { name, path, domains[], prompt? }.
 * Each query: { title, path, domains[], mitre[] }.
 */
export function parseManifest(text) {
    const lines = text.split(/\r?\n/);
    const result = { skills: [], queries: [] };
    let section = null; // "skills" | "queries" | other
    let current = null; // current item object
    let listKey = null; // active list field being appended to

    for (const raw of lines) {
        if (!raw.trim() || raw.trimStart().startsWith("#")) continue;

        // Top-level section header, e.g. "skills:" / "queries:" at column 0.
        const sectionMatch = /^([a-z_]+):\s*$/.exec(raw);
        if (sectionMatch && !raw.startsWith(" ") && !raw.startsWith("-")) {
            section = sectionMatch[1];
            current = null;
            listKey = null;
            continue;
        }

        if (section !== "skills" && section !== "queries") continue;

        // New list item: "- name: value" or "- title: value" at column 0.
        const itemMatch = /^- (name|title):\s?(.*)$/.exec(raw);
        if (itemMatch) {
            current = { domains: [], mitre: [] };
            current[itemMatch[1]] = itemMatch[2].trim();
            listKey = null;
            result[section].push(current);
            continue;
        }

        if (!current) continue;

        // Indented list value: "  - value" (belongs to active listKey).
        const listValMatch = /^\s+-\s+(.*)$/.exec(raw);
        if (listValMatch && listKey) {
            current[listKey].push(listValMatch[1].trim());
            continue;
        }

        // Indented scalar or list-header: "  key: value" / "  key:".
        const kvMatch = /^\s+([a-z_]+):\s?(.*)$/.exec(raw);
        if (kvMatch) {
            const key = kvMatch[1];
            const val = kvMatch[2].trim();
            if (val === "" && (key === "domains" || key === "mitre")) {
                listKey = key;
                current[key] = current[key] || [];
            } else {
                current[key] = val;
                listKey = null;
            }
        }
    }

    return result;
}

/**
 * Consistent lookback windows offered on every skill launch. This is the single
 * source of truth — the UI renders these into a <select> on each card, and
 * composePrompt() injects the chosen window into the chat prompt. An empty value
 * means "let the skill use its own default timeframe" (no injection).
 *
 * Note the 30-day boundary: the repo's KQL pre-flight rule routes >30-day
 * lookbacks to the Data Lake (Advanced Hunting silently truncates to 30d). The
 * skills own that tool decision; the phrase here just states the window clearly.
 */
export const LOOKBACK_OPTIONS = [
    { value: "", label: "Default window" },
    { value: "24h", label: "Last 24 hours", phrase: "the last 24 hours" },
    { value: "7d", label: "Last 7 days", phrase: "the last 7 days" },
    { value: "14d", label: "Last 14 days", phrase: "the last 14 days" },
    { value: "30d", label: "Last 30 days", phrase: "the last 30 days" },
    { value: "90d", label: "Last 90 days", phrase: "the last 90 days" },
];

/** Human phrase for a lookback value, or "" when it's the default/unknown. */
export function lookbackPhrase(value) {
    const opt = LOOKBACK_OPTIONS.find((o) => o.value === (value || "").trim());
    return opt && opt.phrase ? opt.phrase : "";
}

/**
 * Compose the chat prompt for a skill card click. Substitutes {entity} when an
 * entity value is supplied; falls back to a generic "use this skill" prompt for
 * utility skills that carry no canned prompt in the manifest. When a lookback
 * window is chosen, an explicit instruction is appended so the skill overrides
 * its default timeframe consistently.
 */
export function composePrompt(skill, entity, lookback, fleet) {
    let prompt = skill.prompt || UTILITY_SKILL_PROMPTS[skill.name] || `Use the ${skill.name} skill`;
    const fleetCfg = fleet ? FLEET_SCOPE[skill.name] : null;
    if (skill.prompt && skill.prompt.includes("{entity}")) {
        // Fleet-wide replaces {entity} with a whole-fleet phrase; otherwise the
        // analyst's target (or the literal {entity} placeholder when still blank).
        const sub = fleetCfg ? fleetCfg.phrase : ((entity || "").trim() || "{entity}");
        prompt = skill.prompt.replaceAll("{entity}", sub);
    } else if (entity && entity.trim()) {
        prompt = `${prompt} — target: ${entity.trim()}`;
    }
    const phrase = lookbackPhrase(lookback);
    if (phrase) prompt = `${prompt} — use a lookback window of ${phrase}`;
    return prompt;
}

/** True when a skill's prompt expects an entity value from the analyst. */
export function needsEntity(skill) {
    return Boolean(skill.prompt && skill.prompt.includes("{entity}"));
}

/**
 * Resolve a friendly active-tenant label by matching config.json's tenant_id
 * against any local config.json.<name> variants (the user's multi-tenant
 * naming convention). Falls back to a shortened GUID.
 */
async function resolveTenant(repoRoot) {
    let tenantId = null;
    try {
        const cfg = JSON.parse(await readFile(path.join(repoRoot, "config.json"), "utf8"));
        tenantId = cfg.tenant_id || null;
    } catch {
        return { name: "no config.json", tenantId: null };
    }
    if (!tenantId || /^YOUR_/.test(tenantId)) return { name: "unconfigured", tenantId };

    try {
        const entries = await readdir(repoRoot);
        for (const file of entries) {
            const m = /^config\.json\.([A-Za-z0-9_-]+)$/.exec(file);
            if (!m || m[1] === "template") continue;
            try {
                const variant = JSON.parse(await readFile(path.join(repoRoot, file), "utf8"));
                if (variant.tenant_id === tenantId) {
                    return { name: m[1], tenantId };
                }
            } catch {
                /* ignore unreadable variant */
            }
        }
    } catch {
        /* ignore */
    }
    return { name: `${tenantId.slice(0, 8)}…`, tenantId };
}

/** Load everything the canvas UI needs: skills, query stats, tenant context. */
export async function loadCanvasData(repoRoot) {
    const manifestPath = path.join(repoRoot, ".github", "manifests", "discovery-manifest.yaml");
    let manifest = { skills: [], queries: [] };
    try {
        manifest = parseManifest(await readFile(manifestPath, "utf8"));
    } catch (err) {
        return { error: `Could not read discovery manifest: ${err.message}`, skills: [], queries: [], domains: [], tenant: {} };
    }

    // Only surface skills that are launchable (have a prompt or a utility fallback).
    const skills = manifest.skills
        .map((s) => ({
            name: s.name,
            domains: s.domains || [],
            prompt: s.prompt || null,
            hasEntity: needsEntity(s),
            fleet: FLEET_SCOPE[s.name] ? { label: FLEET_SCOPE[s.name].label } : null,
            launchPrompt: composePrompt(s, ""),
            // Query count per domain overlap for a light "coverage" signal.
        }))
        .filter((s) => (s.prompt || UTILITY_SKILL_PROMPTS[s.name]) && !HIDDEN_SKILLS.has(s.name));

    // Domain -> query count, for the domain filter chips.
    const domainQueryCount = {};
    for (const q of manifest.queries) {
        for (const d of q.domains || []) {
            domainQueryCount[d] = (domainQueryCount[d] || 0) + 1;
        }
    }

    const domains = Object.keys(DOMAIN_ICONS).map((d) => ({
        id: d,
        icon: DOMAIN_ICONS[d],
        skillCount: skills.filter((s) => s.domains.includes(d)).length,
        queryCount: domainQueryCount[d] || 0,
    }));

    const tenant = await resolveTenant(repoRoot);

    return {
        error: null,
        skills,
        domains,
        queryTotal: manifest.queries.length,
        tenant,
        lookbackOptions: LOOKBACK_OPTIONS,
    };
}
