// Reads and parses the project's discovery manifest + active tenant context.
// No external YAML dependency — the manifest is machine-generated by
// build_manifest.py with a stable, regular shape, so a small targeted parser
// is sufficient and keeps the extension zero-install.

import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

// Emoji per threat-pulse domain tag (mirrors the repo's Copilot instructions).
export const DOMAIN_ICONS = {
    incidents: "🔴",
    identity: "🔐",
    spn: "🤖",
    endpoint: "🖥️",
    email: "📧",
    admin: "🔑",
    cloud: "☁️",
    exposure: "🛡️",
};

// Skills that have no canned prompt in the manifest but are still worth
// surfacing as launchable cards. Maps skill name -> friendly card metadata.
const UTILITY_SKILL_PROMPTS = {
    "threat-pulse": "Run a Threat Pulse scan across all security domains and give me the prioritized dashboard",
    "kql-query-authoring": "Help me author a KQL query",
    "svg-dashboard": "Generate an SVG dashboard from the latest report",
    "geomap-visualization": "Create a geomap visualization of attack origins",
    "heatmap-visualization": "Create a heatmap visualization of activity patterns",
    "detection-authoring": "Help me create and deploy a custom detection rule",
    "threat-intel-campaign": "Ingest a threat intelligence article and build a hunting campaign",
    "sentinel-ingestion-report": "Run a Sentinel ingestion report — volume, tiers, anomalies, cost",
    "context-memory-review": "Review my tenant-context memory file against the latest scan reports",
};

// Utility skills that shouldn't clutter the launchable grid. They run as part of
// other workflows (e.g. svg-dashboard/geomap/heatmap consume another skill's
// output) or are triggered naturally by chat keywords (kql-query-authoring,
// detection-authoring, threat-intel-campaign, context-memory-review) rather than
// launched cold from a card. Kept in UTILITY_SKILL_PROMPTS so the agent can still
// invoke them, just hidden from the Mission Control grid.
const HIDDEN_SKILLS = new Set([
    "heatmap-visualization",
    "geomap-visualization",
    "svg-dashboard",
    "threat-intel-campaign",
    "kql-query-authoring",
    "detection-authoring",
    "context-memory-review",
]);

// Skills whose {entity} prompt can also run tenant/fleet-wide. When the analyst
// picks "Fleet-wide" on the card, {entity} is replaced with the `phrase` below
// (instead of a single target), so the launched skill sweeps every asset. `label`
// is the short descriptor shown on the card toggle. Keeping this here is the
// single source of truth — the UI reads `fleet` off each skill, and composePrompt
// substitutes the phrase, so the two never drift.
const FLEET_SCOPE = {
    "scope-drift-detection-device": {
        label: "all devices",
        phrase: "the entire device fleet — analyze every device, rank by drift score, and surface the highest-drift outliers",
    },
    "scope-drift-detection-spn": {
        label: "all service principals",
        phrase: "all service principals fleet-wide — rank by drift score and surface the highest-drift outliers",
    },
};

/** Fleet metadata for a skill name, or null when it isn't fleet-capable. */
export function fleetScope(name) {
    return FLEET_SCOPE[name] || null;
}

/**
 * Minimal parser for the slim discovery manifest. Returns { skills, queries }.
 * Each skill: { name, path, domains[], prompt? }.
 * Each query: { title, path, domains[], mitre[] }.
 */
export function parseManifest(text) {
    const lines = text.split(/\r?\n/);
    const result = { skills: [], queries: [] };
    let section = null; // "skills" | "queries" | other
    let current = null; // current item object
    let listKey = null; // active list field being appended to

    for (const raw of lines) {
        if (!raw.trim() || raw.trimStart().startsWith("#")) continue;

        // Top-level section header, e.g. "skills:" / "queries:" at column 0.
        const sectionMatch = /^([a-z_]+):\s*$/.exec(raw);
        if (sectionMatch && !raw.startsWith(" ") && !raw.startsWith("-")) {
            section = sectionMatch[1];
            current = null;
            listKey = null;
            continue;
        }

        if (section !== "skills" && section !== "queries") continue;

        // New list item: "- name: value" or "- title: value" at column 0.
        const itemMatch = /^- (name|title):\s?(.*)$/.exec(raw);
        if (itemMatch) {
            current = { domains: [], mitre: [] };
            current[itemMatch[1]] = itemMatch[2].trim();
            listKey = null;
            result[section].push(current);
            continue;
        }

        if (!current) continue;

        // Indented list value: "  - value" (belongs to active listKey).
        const listValMatch = /^\s+-\s+(.*)$/.exec(raw);
        if (listValMatch && listKey) {
            current[listKey].push(listValMatch[1].trim());
            continue;
        }

        // Indented scalar or list-header: "  key: value" / "  key:".
        const kvMatch = /^\s+([a-z_]+):\s?(.*)$/.exec(raw);
        if (kvMatch) {
            const key = kvMatch[1];
            const val = kvMatch[2].trim();
            if (val === "" && (key === "domains" || key === "mitre")) {
                listKey = key;
                current[key] = current[key] || [];
            } else {
                current[key] = val;
                listKey = null;
            }
        }
    }

    return result;
}

/**
 * Consistent lookback windows offered on every skill launch. This is the single
 * source of truth — the UI renders these into a <select> on each card, and
 * composePrompt() injects the chosen window into the chat prompt. An empty value
 * means "let the skill use its own default timeframe" (no injection).
 *
 * Note the 30-day boundary: the repo's KQL pre-flight rule routes >30-day
 * lookbacks to the Data Lake (Advanced Hunting silently truncates to 30d). The
 * skills own that tool decision; the phrase here just states the window clearly.
 */
export const LOOKBACK_OPTIONS = [
    { value: "", label: "Default" },
    { value: "24h", label: "24h", phrase: "the last 24 hours" },
    { value: "7d", label: "7d", phrase: "the last 7 days" },
    { value: "14d", label: "14d", phrase: "the last 14 days" },
    { value: "30d", label: "30d", phrase: "the last 30 days" },
    { value: "90d", label: "90d", phrase: "the last 90 days" },
];

/** Human phrase for a lookback value, or "" when it's the default/unknown. */
export function lookbackPhrase(value) {
    const opt = LOOKBACK_OPTIONS.find((o) => o.value === (value || "").trim());
    return opt && opt.phrase ? opt.phrase : "";
}

/**
 * Output-format modes offered on every skill launch. Inline is the default and
 * injects nothing — the skills already return an inline chat summary, matching
 * the lookback "empty = no injection" convention. Markdown appends a directive
 * so the skill also writes a saved report file; this pairs with the record_finding
 * directive, which asks for `reports` links in the posted finding.
 */
export const OUTPUT_MODES = [
    { value: "inline", label: "💬 Inline", phrase: "" },
    {
        value: "markdown",
        label: "📄 Markdown",
        phrase: "in addition to a concise inline summary, generate a full Markdown report file, save it under the session's reports folder, and share the saved file path",
    },
];

/** Directive phrase for an output mode, or "" for the default (inline). */
export function outputPhrase(value) {
    const opt = OUTPUT_MODES.find((o) => o.value === (value || "").trim());
    return opt && opt.phrase ? opt.phrase : "";
}

/**
 * Compose the chat prompt for a skill card click. Substitutes {entity} when an
 * entity value is supplied; falls back to a generic "use this skill" prompt for
 * utility skills that carry no canned prompt in the manifest. When a lookback
 * window is chosen, an explicit instruction is appended so the skill overrides
 * its default timeframe consistently.
 */
export function composePrompt(skill, entity, lookback, fleet, output) {
    let prompt = skill.prompt || UTILITY_SKILL_PROMPTS[skill.name] || `Use the ${skill.name} skill`;
    const fleetCfg = fleet ? FLEET_SCOPE[skill.name] : null;
    if (skill.prompt && skill.prompt.includes("{entity}")) {
        // Fleet-wide replaces {entity} with a whole-fleet phrase; otherwise the
        // analyst's target (or the literal {entity} placeholder when still blank).
        const sub = fleetCfg ? fleetCfg.phrase : ((entity || "").trim() || "{entity}");
        prompt = skill.prompt.replaceAll("{entity}", sub);
    } else if (entity && entity.trim()) {
        prompt = `${prompt} — target: ${entity.trim()}`;
    }
    const phrase = lookbackPhrase(lookback);
    if (phrase) prompt = `${prompt} — use a lookback window of ${phrase}`;
    const outPhrase = outputPhrase(output);
    if (outPhrase) prompt = `${prompt} — ${outPhrase}`;
    return prompt;
}

/** True when a skill's prompt expects an entity value from the analyst. */
export function needsEntity(skill) {
    return Boolean(skill.prompt && skill.prompt.includes("{entity}"));
}

/**
 * Resolve a friendly active-tenant label by matching config.json's tenant_id
 * against any local config.json.<name> variants (the user's multi-tenant
 * naming convention). Falls back to a shortened GUID.
 */
async function resolveTenant(repoRoot) {
    let tenantId = null;
    let cfgMemory = "";
    try {
        const cfg = JSON.parse(await readFile(path.join(repoRoot, "config.json"), "utf8"));
        tenantId = cfg.tenant_id || null;
        cfgMemory = memoryFileOf(cfg);
    } catch {
        return withMemory("no config.json", null, cfgMemory);
    }
    if (!tenantId || /^YOUR_/.test(tenantId)) return withMemory("unconfigured", tenantId, cfgMemory);

    try {
        const entries = await readdir(repoRoot);
        for (const file of entries) {
            const m = /^config\.json\.([A-Za-z0-9_-]+)$/.exec(file);
            if (!m || m[1] === "template") continue;
            try {
                const variant = JSON.parse(await readFile(path.join(repoRoot, file), "utf8"));
                if (variant.tenant_id === tenantId) {
                    return withMemory(m[1], tenantId, cfgMemory);
                }
            } catch {
                /* ignore unreadable variant */
            }
        }
    } catch {
        /* ignore */
    }
    return withMemory(`${tenantId.slice(0, 8)}…`, tenantId, cfgMemory);
}

/**
 * Assemble the tenant payload with an EFFECTIVE memory filename. When config.json
 * has no `memory_file`, fall back to a per-tenant default (`<name>-context.md`) so
 * the memory features work on first run without hand-editing JSON. `memoryFileConfigured`
 * tells the UI whether the name is user-set (persisted) or a derived default.
 */
function withMemory(name, tenantId, cfgMemory) {
    return {
        name,
        tenantId,
        memoryFile: cfgMemory || deriveDefaultMemoryFile(name),
        memoryFileConfigured: !!cfgMemory,
    };
}

/** Seed a friendly per-tenant default filename; generic when the label isn't clean. */
function deriveDefaultMemoryFile(name) {
    const clean = String(name || "").trim().toLowerCase();
    const reserved = new Set(["unconfigured", "no config.json"]);
    if (!reserved.has(clean) && /^[a-z0-9_-]+$/.test(clean)) return clean + "-context.md";
    return "tenant-context.md";
}

/**
 * Extract the tenant context-memory filename from a parsed config. It is a bare
 * relative filename resolved under .copilot/memories/repo/ by Copilot's own
 * memory access — the extension never reads the file, it only names it in the
 * injected directive. Guards against the template placeholder and stray paths.
 */
function memoryFileOf(cfg) {
    const raw = String((cfg && cfg.memory_file) || "").trim();
    if (!raw || /^YOUR_/.test(raw)) return "";
    // Keep just the basename — the directive always points at .copilot/memories/repo/.
    return raw.split(/[\\/]/).pop();
}

/** Strip light Markdown (links, emphasis, code, headings) down to plain text. */
function stripMd(s) {
    return String(s || "")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // [text](url) -> text
        .replace(/[*`_#>]+/g, "")                 // bold/italic/code/heading/quote marks
        .replace(/\s+/g, " ")
        .trim();
}

/**
 * Extract a short one-line description + table list from a query .md file.
 * Description sourcing (v1): first sentence of the "## Executive Summary"
 * section; falls back to the "**Keywords:**" header line, then empty.
 */
export function parseQueryDoc(text) {
    const lines = String(text || "").split(/\r?\n/);

    // Tables from the standardized header line, e.g. "**Tables:** A, B, C".
    let tables = [];
    for (const l of lines.slice(0, 40)) {
        const m = /^\*\*Tables:\*\*\s*(.+)$/.exec(l.trim());
        if (m) { tables = m[1].split(",").map((s) => s.trim()).filter(Boolean); break; }
    }

    // Description: first paragraph under the Executive Summary heading.
    let desc = "";
    const idx = lines.findIndex((l) => /^#{2,}\s+Executive Summary\b/i.test(l.trim()));
    if (idx >= 0) {
        const buf = [];
        for (let i = idx + 1; i < lines.length; i++) {
            const t = lines[i].trim();
            if (/^#{1,6}\s/.test(t)) break;                 // next heading ends the section
            if (/^---+$/.test(t)) { if (buf.length) break; else continue; }
            if (!t) { if (buf.length) break; else continue; } // blank after content = end of first para
            buf.push(t);
        }
        desc = buf.join(" ");
    }
    if (!desc) {
        for (const l of lines.slice(0, 40)) {
            const m = /^\*\*Keywords:\*\*\s*(.+)$/.exec(l.trim());
            if (m) { desc = m[1].trim(); break; }
        }
    }

    desc = stripMd(desc);
    const firstSentence = (desc.split(/(?<=\.)\s+/)[0] || desc).trim();
    if (firstSentence.length > 240) desc = firstSentence.slice(0, 237).trimEnd() + "…";
    else desc = firstSentence;

    return { description: desc, tables };
}

/**
 * Enrich the manifest's query entries with a description + table list read from
 * each file. Files missing on disk are still listed (without a description).
 */
async function loadQueries(repoRoot, manifestQueries) {
    const out = [];
    for (const q of manifestQueries || []) {
        let meta = { description: "", tables: [] };
        try {
            meta = parseQueryDoc(await readFile(path.join(repoRoot, q.path), "utf8"));
        } catch {
            // Listed in the manifest but unreadable — surface it anyway.
        }
        out.push({
            title: q.title || (q.path.split("/").pop() || "").replace(/\.md$/i, ""),
            path: q.path,
            domains: q.domains || [],
            mitre: q.mitre || [],
            tables: meta.tables,
            description: meta.description,
        });
    }
    out.sort(
        (a, b) =>
            (a.domains[0] || "").localeCompare(b.domains[0] || "") ||
            a.title.localeCompare(b.title)
    );
    return out;
}

/**
 * Load the vendored ATT&CK reference (mitre-coverage-report skill) and reshape it
 * into a compact, kill-chain-ordered matrix the canvas can render:
 *   { version, tactics: [ { name, shortname, techniques: [ { id, name } ] } ] }
 * The source keys its `tactics` object in kill-chain order; JSON.parse preserves
 * that order, so Object.values gives the correct column sequence. Base techniques
 * only (no sub rows); multi-tactic techniques are already repeated per tactic in
 * the source, which we preserve so a tile shows in each of its columns.
 * Returns null on any failure so the canvas degrades gracefully.
 */
async function loadMitreMatrix(repoRoot) {
    try {
        const refPath = path.join(
            repoRoot,
            ".github", "skills", "mitre-coverage-report", "mitre-attck-enterprise.json"
        );
        const ref = JSON.parse(await readFile(refPath, "utf8"));
        const src = ref && ref.tactics ? ref.tactics : {};
        const tactics = Object.values(src).map((t) => ({
            name: t.displayName || "",
            shortname: t.shortname || "",
            techniques: (t.techniques || []).map((k) => ({ id: k.id, name: k.name })),
        }));
        if (!tactics.length) return null;
        return { version: ref.version || "", tactics };
    } catch {
        return null;
    }
}

/** Load everything the canvas UI needs: skills, queries, tenant context. */
export async function loadCanvasData(repoRoot) {
    const manifestPath = path.join(repoRoot, ".github", "manifests", "discovery-manifest.yaml");
    let manifest = { skills: [], queries: [] };
    try {
        manifest = parseManifest(await readFile(manifestPath, "utf8"));
    } catch (err) {
        return { error: `Could not read discovery manifest: ${err.message}`, skills: [], queries: [], domains: [], tenant: {} };
    }

    // Only surface skills that are launchable (have a prompt or a utility fallback).
    const skills = manifest.skills
        .map((s) => ({
            name: s.name,
            path: s.path || null,
            domains: s.domains || [],
            prompt: s.prompt || null,
            hasEntity: needsEntity(s),
            fleet: FLEET_SCOPE[s.name] ? { label: FLEET_SCOPE[s.name].label } : null,
            launchPrompt: composePrompt(s, ""),
            // Query count per domain overlap for a light "coverage" signal.
        }))
        .filter((s) => (s.prompt || UTILITY_SKILL_PROMPTS[s.name]) && !HIDDEN_SKILLS.has(s.name));

    // Domain -> query count, for the domain filter chips.
    const domainQueryCount = {};
    for (const q of manifest.queries) {
        for (const d of q.domains || []) {
            domainQueryCount[d] = (domainQueryCount[d] || 0) + 1;
        }
    }

    const domains = Object.keys(DOMAIN_ICONS).map((d) => ({
        id: d,
        icon: DOMAIN_ICONS[d],
        skillCount: skills.filter((s) => s.domains.includes(d)).length,
        queryCount: domainQueryCount[d] || 0,
    }));

    const tenant = await resolveTenant(repoRoot);
    const queries = await loadQueries(repoRoot, manifest.queries);
    const mitre = await loadMitreMatrix(repoRoot);

    return {
        error: null,
        skills,
        domains,
        queries,
        queryTotal: manifest.queries.length,
        tenant,
        mitre,
        lookbackOptions: LOOKBACK_OPTIONS,
        outputModes: OUTPUT_MODES,
    };
}
